# Generated by Django 4.0.3 on 2022-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chacara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chacara',
            name='imagem',
            field=models.ImageField(upload_to='chacaras'),
        ),
    ]
