# Generated by Django 4.0.3 on 2022-03-15 19:05

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chacara', '0002_alter_chacara_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chacara',
            name='data_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='chacara',
            name='descricao_curta',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chacara',
            name='espaco',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chacara',
            name='facebook',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_1',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_2',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_3',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_4',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_5',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_6',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_7',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='imagem_8',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chacara',
            name='instagram',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chacara',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chacara',
            name='outros_recursos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chacara',
            name='pagamentos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('Cartão Parcelado', 'Cartão Parcelado'), ('PIX', 'PIX')], max_length=36),
        ),
        migrations.AddField(
            model_name='chacara',
            name='pontos_referencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Açougue', 'Açougue'), ('Bar / Lanchonete', 'Bar / Lanchonete'), ('Distribuidora de Bebidas', 'Distribuidora de Bebidas'), ('Mercearia', 'Mercearia'), ('Padaria', 'Padaria'), ('Ponto de Onibus', 'Ponto de Onibus'), ('Supermercado', 'Supermercado')], max_length=96),
        ),
        migrations.AddField(
            model_name='chacara',
            name='recursos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Acesso para Cadeirantes', 'Acesso para Cadeirantes'), ('Aquecedor', 'Aquecedor'), ('Ar condicionado no Salão', 'Ar condicionado no Salão'), ('Area para Camping', 'Area para Camping'), ('Area verde', 'Area verde'), ('Banheiros Masculino e Feminino', 'Banheiros Masculino e Feminino'), ('Banheiro Unissex', 'Banheiro Unissex'), ('Cachoeira', 'Cachoeira'), ('Campo de Futebol', 'Campo de Futebol'), ('Cervejeira', 'Cervejeira'), ('Cozinha equipada', 'Cozinha equipada'), ('Churrasqueira', 'Churrasqueira'), ('Dormitórios', 'Dormitórios'), ('Dormitórios com Ar condicionado', 'Dormitórios com Ar condicionado'), ('Escorregador na piscina', 'Escorregador na piscina'), ('Estacionamento', 'Estacionamento'), ('Freezer', 'Freezer'), ('Frente para Rio/Lago', 'Frente para Rio/Lago'), ('Localizado em Condominio', 'Localizado em Condominio'), ('Playground', 'Playground'), ('Piscina', 'Piscina'), ('Piscina Aquecida', 'Piscina Aquecida'), ('Piscina Coberta', 'Piscina Coberta'), ('Piscina Infantil', 'Piscina Infantil'), ('Pista de dança', 'Pista de dança'), ('Proibido animais', 'Proibido animais'), ('Proibido som Automotivo', 'Proibido som Automotivo'), ('Quadra de Areia', 'Quadra de Areia'), ('Quadra de Bocha', 'Quadra de Bocha'), ('Quadra de Tenis', 'Quadra de Tenis'), ('Rede de Volley na piscina', 'Rede de Volley na piscina'), ('Segurança', 'Segurança'), ('Sofás', 'Sofás'), ('Trilha Ecológica', 'Trilha Ecológica'), ('Vestiário', 'Vestiário'), ('Ventiladores', 'Ventiladores')], max_length=596),
        ),
        migrations.AddField(
            model_name='chacara',
            name='telefone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chacara',
            name='tipo_eventos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Aniversário', 'Aniversário'), ('Casamentos', 'Casamentos'), ('Confraternização', 'Confraternização'), ('Festa Infantil', 'Aniversário Infantil'), ('Formatura', 'Formatura'), ('Outros', 'Outros')], max_length=71),
        ),
        migrations.AddField(
            model_name='chacara',
            name='video_link',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chacara',
            name='whatsapp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chacara',
            name='capacidade',
            field=models.CharField(blank=True, choices=[('Até 25 pessoas', 'Até 25 pessoas'), ('Até 50 pessoas', 'Até 50 pessoas'), ('Até 100 pessoas', 'Até 100 pessoas'), ('Até 150 pessoas', 'Até 150 pessoas'), ('Até 200 ou mais pessoas', 'Até 200 ou mais pessoas')], max_length=300),
        ),
        migrations.AlterField(
            model_name='chacara',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chacara',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100),
        ),
        migrations.AlterField(
            model_name='chacara',
            name='imagem',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
